[project]
name = "httpcache"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diskcache>=5.6.3",
    "redis>=6.4.0",
    "requests>=2.32.4",
    "requests-toolbelt>=1.0.0",
]
